---
title: "Assignment 2_DV"
author: ""
date: "06/03/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r echo=TRUE, message=FALSE, warning=FALSE}

library(ggplot2) #importing library ggplot
mydata<- mtcars
mydata$cyl<- as.factor(mydata$cyl)

#plot1
plot1 <- ggplot(mydata, aes(x=mpg, y=wt, colour=cyl, shape=cyl)) +geom_point(size=3)+ theme_bw()
plot1

#plot2
ColorBPalette <- c("#000000","#E69F00","#56B4E9","#009E73","#F0E442","#0072B2","#D55E00","#CC79A7")
plot2 <- ggplot(mydata, aes(x=mpg, y=wt, colour=cyl, shape=cyl)) +geom_point(size=3)+ 
  scale_color_manual(values=ColorBPalette)+ theme_bw()
plot2

#plot3
#install.packages("viridis") #installing viridis
library(viridis) #importing viridis library
plot3 <- ggplot(mydata, aes(x=mpg, y=wt, colour=cyl, shape=cyl)) +geom_point(size=3)+ 
  scale_color_viridis_d()+ theme_bw()
plot3

#installing cowplot and colorspace
#devtools::install_github("wilkelab/cowplot", force=TRUE)
#install.packages("colorspace",repos="http://R-Forge.R-project.org")
#devtools::install_github("clauswilke/colorblindr",force = TRUE) #installing colorblindr
library(colorblindr) #importing colorblindr library

#plot4
cvd_grid(plot1)

#plot5
cvd_grid(plot2)

#plot6
cvd_grid(plot3)

```

